// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab8_DBEF.Models;

#nullable disable

namespace lab8_DBEF.Migrations
{
    [DbContext(typeof(DbAeroklub))]
    partial class DbAeroklubModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lab8_DBEF.Models.Samolot", b =>
                {
                    b.Property<int>("SamolotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SamolotId"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Model");

                    b.Property<double>("Predkosc")
                        .HasColumnType("float")
                        .HasColumnName("Predkosc");

                    b.Property<string>("Producent")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Producent");

                    b.Property<double>("Pulap")
                        .HasColumnType("float")
                        .HasColumnName("Pulap");

                    b.Property<double>("Udzwig")
                        .HasColumnType("float")
                        .HasColumnName("Udzwig");

                    b.HasKey("SamolotId");

                    b.ToTable("Samoloty");
                });
#pragma warning restore 612, 618
        }
    }
}
